//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaRopa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedidoProveedor
    {
        public int IdDetallePedidoProveedor { get; set; }
        public Nullable<int> IdPedidoProveedor { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
    
        public virtual PedidoProveedor PedidoProveedor { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
