//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaRopa.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    public partial class Devolucion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Devolucion()
        {
            this.DetalleDevolucions = new HashSet<DetalleDevolucion>();
        }
    
        public int IdDevolucion { get; set; }
        public Nullable<int> IdVenta { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Motivo { get; set; }

        [JsonIgnore]
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleDevolucion> DetalleDevolucions { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
