//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaRopa.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class PedidoProveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidoProveedor()
        {
            this.DetallePedidoProveedors = new HashSet<DetallePedidoProveedor>();
        }
    
        public int IdPedidoProveedor { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public string Estado { get; set; }
    
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePedidoProveedor> DetallePedidoProveedors { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
